### PR TITLE
required-packages in viz.yaml

### PR DESCRIPTION
**Pull request by lindsaycarr**
vizSkeleton now creates an element called `required-packages` that will be a collection of the packages needed to run this visualization. `vizlab` is automatically added as the first package.

e.g. `required-packages: vizlab, gsplot, dataRetrieval`

fixing part of #91

### CODE REVIEW

**Comment by wdwatkins** [comment]
Wouldn't you have to have vizlab installed already to run this function?

**Comment by lindsaycarr** [comment]
yes, this is just a section stating what packages the viz uses to users. It doesn't install or load anything. Just for documentation

**Comment by wdwatkins** [comment]
Ok.  It seems like we might want to have a function that loads packages based on this, but it could just know to skip vizlab then.  We probably want to have some system to provide corresponding repos for each package, at least if it isn't CRAN

**Comment by lindsaycarr** [comment]
Yes, but we decided per #91, that we would start with just a place to define things since we couldn't come to consensus about how to load.

**Comment by wdwatkins** [comment]
Sorry, I just meant the loading function could be a possible feature that would utilize this list, not that you should add it right now.  But for listing things, the repo and/or version could be important to know also.   This is fine to start with though.

**Comment by lindsaycarr** [comment]
ah now I see what you mean. Hmmm...let me think about how I could add that.

**Comment by lindsaycarr** [comment]
Ok, here's an idea for including different repositories. Any ideas about how to get the version on there @wdwatkins ?

```
required-packages:
    cran: dataRetrieval
    gran: vizlab
    github: USGS-R/gsplot
```

**Comment by wdwatkins** [comment]
I was thinking something like that, but then the only way I can think of would be to have a corresponding versions vector, which seems pretty clunky:

```
required-packages:
    cran: dataRetrieval
         versions: xxx 
    gran: vizlab
         versions: xxx
```

Another way might be to make each package its own thing, but that would make the viz.yaml get really long:

```
required-packages:
        dataRetrieval:
                repo: GRAN
                version: xxx
       github:
                 repo: github
                 version:  yyy
```

**Comment by lindsaycarr** [comment]
Let's see which @jiwalker-usgs likes best when he gets back (not a difficult change to merge the day before we kick off the viz)

**Comment by jiwalker-usgs** [comment]
I think I like the last option best:
```
required-packages:
  dataRetrieval:
    repo: GRAN
    version: xxx
  github:
    repo: github
    name: cscheid/rgithub
    version: yyy
```

Though repo GRAN is ambiguous in this case.  We'd want to define the repo options before attempting to automate anything out of this.

**Comment by jread-usgs** [comment]
use `tag` instead of `version` for github?

**Comment by aappling-usgs** [comment]
Yeah, or `ref` because that's what `install_github` uses? https://www.rdocumentation.org/packages/devtools/versions/1.12.0/topics/install_github

**Comment by jread-usgs** [comment]
yeah, that is better. the version is ambiguous because `intall_github` is based on tags or commits, and you can tag `1.0.0` when the actual version of the package is totally different. `ref` allows us to cover tags and commits and be consistent there.

**Comment by jiwalker-usgs** [comment]
I propose that we work through this section in the new viz and backport what we come up with into the skeleton.  I also think that calling out vizlab in this section might be weird to @wdwatkins point, so we should discuss that further.

**Comment by jiwalker-usgs** [comment]
I'm going to close this for now, we can revive it after this viz and a discussion on the pattern we want going forward.

**Comment by aappling-usgs** [comment]
Oh, I see why these changes got lost - they never got merged! I will add them again as I'm working through  #123

**Comment by lindsaycarr** [comment]
Ahhh yes, that would do it :)

**Pull request closed without merging**
