### PR TITLE
Timestamps

### PR DESCRIPTION
**Pull request by aappling-usgs**
Timestamp checking is working.

Here's my best visual explanation of how vizlab treats file currency and timestamps so far (needs work, but it's a start):
image

The timestamp functionality is demonstrated in https://github.com/USGS-VIZLAB/vizlab/pull/316/files#diff-3066b18354ab4c8e1b10c0daa72dbcfe

I also updated the vignettes.

### CODE REVIEW

**Comment by aappling-usgs** [comment]
tests work when run at console but fail w ctrl-shift-t. pushing here to see how travis does with it

**Comment by aappling-usgs** [comment]
It works! Sorry for the giant PR, but it's what was needed to get timestamps handled and properly tested...OK, and getting the testviz a bit more compliant with the style guide too. it's probably easiest to start with the tests to see how the package is supposed to behave. @ldecicco-USGS , do you have time to review this?

**Comment by aappling-usgs** [comment]
also, `createRemakefiles` is atrociously long and i know it. i'm working on a refactor for an upcoming PR

**Comment by aappling-usgs** [comment]
Here's the cleaned-up version of createRemakefiles: https://github.com/aappling-usgs/vizlab/compare/timestamps...aappling-usgs:parameters?expand=1#diff-3100aa6afab755cba48769133597a7a8. I'm not sure how to create a clean PR for it before this one is merged because it depends on this one, but I'll create it as soon as we're through with this one.

**Comment by ldecicco-USGS** [comment]
Pulled it down, seemed to work as I expect. Super cool

**Pull request merged**
