### PR TITLE
Fix Alison's silliness

### PR DESCRIPTION
**Pull request by aappling-usgs**
ok @lindsaycarr , let's try this.

### CODE REVIEW

**Comment by lindsaycarr** [comment]
The Jenkins build said "ran for about 15 hours" and the log was empty. If you click the raw log, the only thing in the file is the word "null". I'm going to attribute this to their slowness yesterday and see if close/open of this PR will kick things off and actually show logs.

**Comment by aappling-usgs** [comment]
I guess I wasn't the only one being silly this week =)

**Comment by aappling-usgs** [comment]
Yep, those are the same ScienceBase errors we were seeing 7 days ago. Identical in https://travis-ci.org/USGS-VIZLAB/vizlab/builds/327267589 and https://travis-ci.org/USGS-VIZLAB/vizlab/builds/330015134: 
```
checking tests ... ERROR
  Running ‘testthat.R’ [8s/17s]
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  file.exists(tsfile) isn't true.
  
  ── 2. Failure: sciencebase works (@tests-timestamps.R#118)  ────────────────────
  `ts1` not equal to as.POSIXct("2016-06-12 15:50:15", tz = "UTC").
  Modes: logical, numeric
  Attributes: < target is NULL, current is list >
  target is logical, current is POSIXct
  
  ══ testthat results  ═══════════════════════════════════════════════════════════
  OK: 128 SKIPPED: 2 FAILED: 2
  1. Failure: sciencebase works (@tests-timestamps.R#115) 
  2. Failure: sciencebase works (@tests-timestamps.R#118) 
  
  Error: testthat unit tests failed
  Execution haltedchecking package dependencies ... NOTE
Package suggested but not available for checking: ‘dssecrets’
```

**Comment by lindsaycarr** [comment]
Merging since we can ignore ScienceBase errors for now (see #327)

**Pull request merged**
