### PR TITLE
vizlab to match water use footer

### PR DESCRIPTION
**Pull request by mwernimont**
@jiwalker-usgs Took the template from water use and put it in the inst footer template, and then switched the vizlab footer CSS for the water use footer CSS.

### CODE REVIEW

**Comment by jiwalker-usgs** [comment]
I think this dropped the related blog posts that were optional in the old format.

**Comment by mwernimont** [comment]
@jiwalker-usgs Look better?

**Comment by jiwalker-usgs** [comment]
Close, because the blogs are optional there was a boolean that enabled that section.

**Comment by mwernimont** [comment]
@jiwalker-usgs How's that? Want me to remove that other file from the PR?

**Pull request merged**
