### PR TITLE
Correctly getting the github url in there

### PR DESCRIPTION
**Pull request by ldecicco-USGS**

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
Fixes #339

**Comment by ldecicco-USGS** [comment]
FYI, the testthat failures I get are still the timestamp issues we've been seeing.

**Comment by aappling-usgs** [comment]
Are you getting those testthat failures locally, Laura? Looks like we're now getting mixed messages from Travis - the [PRs have been building successfully](https://travis-ci.org/USGS-VIZLAB/vizlab/pull_requests) while the [merges have been timing out](https://travis-ci.org/USGS-VIZLAB/vizlab/builds). I don't understand how those classes of Travis tests differ, but this new pattern seems slightly better than everything failing...and the failures are no longer pointing directly to sciencebase timestamps, at least.... #327

**Comment by ldecicco-USGS** [comment]
Yes, I was getting those locally

**Comment by aappling-usgs** [comment]
Any chance you're now just getting `crayon` errors, not sciencebase timestamp ones? see https://github.com/USGS-VIZLAB/vizlab/issues/327#issuecomment-369628206 for what i think our current status is. and if you're getting something different from me, could you paste your current messages into that issue?

**Comment by ldecicco-USGS** [comment]
Yup, that's it!

**Pull request merged**
