### PR TITLE
mimetypes lookup dictionary + 508 compliance

### PR DESCRIPTION
**Pull request by lindsaycarr**
Working on #39 and #36

### CODE REVIEW

**Comment by lindsaycarr** [comment]
Still need a way for someone to specify a different mimetype config file

**Comment by lindsaycarr** [comment]
@jiwalker-usgs for someone to specify their own dictionary, I am thinking they should need to add a field to their viz.yaml for each section in fetch that is called `mimetypeDictionary` or `mimetypeLookup` or something. Thoughts?

note to self -- would need to add a test to see if that works for the package

**Comment by jiwalker-usgs** [comment]
I think rather than each section defining additional mimetypes, this could live in the root of the viz.yaml as more mimetypes for the particular viz.

**Comment by jiwalker-usgs** [comment]
Also, there is a similar mimetype lookup in the publish section, can we get that to follow this pattern as well.

**Pull request merged**
