### PR TITLE
Working on Linux

### PR DESCRIPTION
**Pull request by jiwalker-usgs**
Still need to double check Windows

### CODE REVIEW

**Comment by lindsaycarr** [comment]
@jiwalker-usgs recommendation for the best way to test? Run `createMakefiles`?

**Comment by jiwalker-usgs** [comment]
Yeah, run that and do a make on testviz.

**Comment by lindsaycarr** [comment]
@jiwalker-usgs I get that same `couldn't make stderr distinct from stdout` error everywhere, and then I get `Error 1` for figures/relativeAbundanceFig.svg and `Error 2` at the very end. Not sure if this passes the issue you were seeing and is just a separate issue in testviz or not.

In console:
```r
setwd('inst/testviz')
createMakefiles()
```

Then, in Git shell:

```
lcarr@IGSARMEWLTLRC /d/LRCData/R/vizlab (jiwalker-usgs-master)
$ cd inst/testviz

lcarr@IGSARMEWLTLRC /d/LRCData/R/vizlab/inst/testviz (jiwalker-usgs-master)
$ make
make -f vizlab/make/fetch.make
      0 [main] sh 8412 stdio_init: couldn't make stderr distinct from stdout
make[1]: Entering directory `/cygdrive/d/LRCData/R/vizlab/inst/testviz'
export R_LIBS_USER=C:/Users/lcarr/Documents/R/R-3.3.2/library;\
C:/Users/lcarr/Documents/R/R-3.3.2/bin/x64/R.exe CMD BATCH --no-timing --quiet -
-no-save --no-restore "--args fun=fetchTimestamp funargs=list(viz='siteTextData'
)" \
vizlab/make/callFunction.R vizlab/make/log/fetch/siteTextData_timestamp.Rout
      0 [main] sh 7736 stdio_init: couldn't make stderr distinct from stdout
export R_LIBS_USER=C:/Users/lcarr/Documents/R/R-3.3.2/library;\
C:/Users/lcarr/Documents/R/R-3.3.2/bin/x64/R.exe CMD BATCH --no-timing --quiet -
-no-save --no-restore "--args fun=fetch funargs=list(viz='siteTextData')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/siteTextData.Rout
      0 [main] sh 2816 stdio_init: couldn't make stderr distinct from stdout
export R_LIBS_USER=C:/Users/lcarr/Documents/R/R-3.3.2/library;\
C:/Users/lcarr/Documents/R/R-3.3.2/bin/x64/R.exe CMD BATCH --no-timing --quiet -
-no-save --no-restore "--args fun=fetch funargs=list(viz='Cuyahoga')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/Cuyahoga.Rout
      0 [main] sh 8368 stdio_init: couldn't make stderr distinct from stdout
export R_LIBS_USER=C:/Users/lcarr/Documents/R/R-3.3.2/library;\
C:/Users/lcarr/Documents/R/R-3.3.2/bin/x64/R.exe CMD BATCH --no-timing --quiet -
-no-save --no-restore "--args fun=fetchTimestamp funargs=list(viz='MayflyNymph')
 scripts=c('scripts/fetch/mayflyNymph.R')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/MayflyNymph_timestamp.Rout
      0 [main] sh 6184 stdio_init: couldn't make stderr distinct from stdout
export R_LIBS_USER=C:/Users/lcarr/Documents/R/R-3.3.2/library;\
C:/Users/lcarr/Documents/R/R-3.3.2/bin/x64/R.exe CMD BATCH --no-timing --quiet -
-no-save --no-restore "--args fun=fetch funargs=list(viz='MayflyNymph') scripts=
c('scripts/fetch/mayflyNymph.R')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/MayflyNymph.Rout
      0 [main] sh 264 stdio_init: couldn't make stderr distinct from stdout
export R_LIBS_USER=C:/Users/lcarr/Documents/R/R-3.3.2/library;\
C:/Users/lcarr/Documents/R/R-3.3.2/bin/x64/R.exe CMD BATCH --no-timing --quiet -
-no-save --no-restore "--args fun=fetchTimestamp funargs=list(viz='carData')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/carData_timestamp.Rout
      0 [main] sh 2344 stdio_init: couldn't make stderr distinct from stdout
export R_LIBS_USER=C:/Users/lcarr/Documents/R/R-3.3.2/library;\
C:/Users/lcarr/Documents/R/R-3.3.2/bin/x64/R.exe CMD BATCH --no-timing --quiet -
-no-save --no-restore "--args fun=fetch funargs=list(viz='carData')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/carData.Rout
      0 [main] sh 8424 stdio_init: couldn't make stderr distinct from stdout
export R_LIBS_USER=C:/Users/lcarr/Documents/R/R-3.3.2/library;\
C:/Users/lcarr/Documents/R/R-3.3.2/bin/x64/R.exe CMD BATCH --no-timing --quiet -
-no-save --no-restore "--args fun=fetch funargs=list(viz='constant')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/constant.Rout
      0 [main] sh 5232 stdio_init: couldn't make stderr distinct from stdout
export R_LIBS_USER=C:/Users/lcarr/Documents/R/R-3.3.2/library;\
C:/Users/lcarr/Documents/R/R-3.3.2/bin/x64/R.exe CMD BATCH --no-timing --quiet -
-no-save --no-restore "--args fun=fetch funargs=list(viz='constant-list')" \
vizlab/make/callFunction.R vizlab/make/log/fetch/constant-list.Rout
      0 [main] sh 3684 stdio_init: couldn't make stderr distinct from stdout
      0 [main] sh 4296 stdio_init: couldn't make stderr distinct from stdout

      0 [main] sh 8836 stdio_init: couldn't make stderr distinct from stdout
fetch.make looks OK!
      0 [main] sh 4176 stdio_init: couldn't make stderr distinct from stdout

make[1]: Leaving directory `/cygdrive/d/LRCData/R/vizlab/inst/testviz'
make -f vizlab/make/process.make
      0 [main] sh 2816 stdio_init: couldn't make stderr distinct from stdout
make[1]: Entering directory `/cygdrive/d/LRCData/R/vizlab/inst/testviz'
export R_LIBS_USER=C:/Users/lcarr/Documents/R/R-3.3.2/library;\
C:/Users/lcarr/Documents/R/R-3.3.2/bin/x64/R.exe CMD BATCH --no-timing --quiet -
-no-save --no-restore "--args fun=process funargs=list(viz='CuyahogaShort') scri
pts=c('scripts/process/cuyahoga.R')" \
vizlab/make/callFunction.R vizlab/make/log/process/CuyahogaShort.Rout
      0 [main] sh 8692 stdio_init: couldn't make stderr distinct from stdout
      0 [main] sh 4164 stdio_init: couldn't make stderr distinct from stdout

      0 [main] sh 9160 stdio_init: couldn't make stderr distinct from stdout
process.make looks OK!
      0 [main] sh 7956 stdio_init: couldn't make stderr distinct from stdout

make[1]: Leaving directory `/cygdrive/d/LRCData/R/vizlab/inst/testviz'
make -f vizlab/make/visualize.make
      0 [main] sh 1664 stdio_init: couldn't make stderr distinct from stdout
make[1]: Entering directory `/cygdrive/d/LRCData/R/vizlab/inst/testviz'
export R_LIBS_USER=C:/Users/lcarr/Documents/R/R-3.3.2/library;\
C:/Users/lcarr/Documents/R/R-3.3.2/bin/x64/R.exe CMD BATCH --no-timing --quiet -
-no-save --no-restore "--args fun=visualize funargs=list(viz='relativeAbundanceF
ig')" \
vizlab/make/callFunction.R vizlab/make/log/visualize/relativeAbundanceFig.Rout
      0 [main] sh 8120 stdio_init: couldn't make stderr distinct from stdout
make[1]: *** [figures/relativeAbundanceFig.svg] Error 1
make[1]: Leaving directory `/cygdrive/d/LRCData/R/vizlab/inst/testviz'
make: *** [visualize] Error 2
```

**Comment by jiwalker-usgs** [comment]
Those are red herrings, has something to do with your shell I think.  But I do think that it is failing on that figure.  I think my fix should be fine (that it got this far), but I wonder what is causing that to fail.

**Comment by lindsaycarr** [comment]
I'll look in the make logs and let you know.

**Comment by lindsaycarr** [comment]
For fig:

```r
> do.call(cmd.args$fun, if(is.null(cmd.args$funargs)) list() else cmd.args$funargs)
Error in UseMethod("visualize") : 
  no applicable method for 'visualize' applied to an object of class "c('relativeAbundance', 'visualizer', 'viz')"
Calls: do.call -> <Anonymous> -> visualize.character -> visualize
Execution halted
```

**Comment by jiwalker-usgs** [comment]
Yeah, I don't know how that worked for me, that signature is all wrong.

**Comment by lindsaycarr** [comment]
Merging, but we will make a ticket to get the testviz working.

**Pull request merged**
