### PR TITLE
named depends in testviz viz.yaml

### PR DESCRIPTION
**Pull request by wdwatkins**

### CODE REVIEW

**Comment by wdwatkins** [comment]
An approach to #92

**Comment by wdwatkins** [comment]
@jiwalker-usgs @jread-usgs @lindsaycarr If we take this approach maybe we should have a naming convention for the different depends items?

**Comment by lindsaycarr** [comment]
Wouldn't they just be the id of the thing it's referring to?

**Comment by wdwatkins** [comment]
That would be one option, although we could conceivably want to use something more general in case we changed what the dependencies were (i.e. a generic 'data' dependency or something).

**Comment by jiwalker-usgs** [comment]
I think the names should be descriptive of what they are used for, and a convention is a good idea in general so we don't have to second guess ourselves in looking back.  I've avoided using CAPITAL letters in the yaml keys, though that is just one possibility.

**Pull request merged**
