### PR TITLE
cscheid/rgithub --> GRAN: grithub

### PR DESCRIPTION
**Pull request by lindsaycarr**
needed for landing page

### CODE REVIEW

**Comment by lindsaycarr** [comment]
ack - failed on installing `grithub`. @ldecicco-USGS how can I have it specifically install `grithub` from GRAN for the build?

**Comment by ldecicco-USGS** [comment]
See instructions here :)
https://owi.usgs.gov/R/gran.html

```
install.packages("grithub", repos=c("https://owi.usgs.gov/R"))

```

**Comment by ldecicco-USGS** [comment]
OHHH...you mean on travis!

**Comment by ldecicco-USGS** [comment]
Maybe check out @aappling-usgs 's streamMetabolizer travis:

```
r_build_args: --no-build-vignettes --no-manual --no-multiarch
r_check_args: --no-build-vignettes --no-manual

repos:
  CRAN: https://cloud.r-project.org
  GRAN: http://owi.usgs.gov/R

before_script:
  - Rscript -e "install.packages('knitr', repos='http://cran.cnr.Berkeley.edu/')"
  - Rscript -e "install.packages('rmarkdown', repos='http://cran.cnr.Berkeley.edu/')"

r_packages:
 - modeest
 - deSolve

r_github_packages:
 - jimhester/covr
 - GLEON/LakeMetabolizer
- appling/unitted

```

**Comment by lindsaycarr** [comment]
Yeah, on Travis

**Comment by lindsaycarr** [comment]
Yeah, but ours already has GRAN as a repo, so grithub should be able to be installed. Hmmm

**Comment by ldecicco-USGS** [comment]
I'd add in the before_script Rscript line.

**Pull request merged**
