### PR TITLE
add google analytics to landing

### PR DESCRIPTION
**Pull request by wdwatkins**

### CODE REVIEW

**Comment by aappling-usgs** [comment]
This would resolve https://github.com/USGS-VIZLAB/vizlab/issues/261, right?

**Comment by wdwatkins** [comment]
yes

**Comment by wdwatkins** [comment]
Looking at this again, I'm not sure what this index.html is actually doing.  It isn't a template, and it isn't what gets rendered.

**Comment by aappling-usgs** [comment]
Yikes! Good to know. Glad to see you and Marty making progress on this at https://github.com/USGS-VIZLAB/vizlab/pull/269.

**Comment by ldecicco-USGS** [comment]
When you run the function, you have to look in the landing folder, then the target folder...then index.html. For whatever reason, there's some *other* index.html in the landing folder just to throw us off I think.

**Comment by wdwatkins** [comment]
Yeah, I'm deleting the decoy index.html in my current PR

**Pull request merged**
