### PR TITLE
add d3-scale-chromatic library

### PR DESCRIPTION
**Pull request by lindsaycarr**

### CODE REVIEW

**Comment by lindsaycarr** [comment]
I believe this failed build might be a network thing because of sciencebase:

```
  ── 2. Failure: sciencebase works (@tests-timestamps.R#118)  ────────────────────
  `ts1` not equal to as.POSIXct("2016-06-12 15:50:15", tz = "UTC").
  Modes: logical, numeric
  Attributes: < target is NULL, current is list >
  target is logical, current is POSIXct
  
  ══ testthat results  ═══════════════════════════════════════════════════════════
  OK: 128 SKIPPED: 2 FAILED: 2
  1. Failure: sciencebase works (@tests-timestamps.R#115) 
  2. Failure: sciencebase works (@tests-timestamps.R#118) 
```

**Comment by lindsaycarr** [comment]
The network has been kind of weird this afternoon. I'm going to try again in the morning.

**Comment by ldecicco-USGS** [comment]
I think this has been a thorn in our side for awhile

**Comment by ldecicco-USGS** [comment]
It sure sounds like something @aappling-usgs and I were struggling with this summer (?)....maybe she can remember off-hand

**Comment by lindsaycarr** [comment]
Closing then re-opening to kick off again. I am getting some failures locally but they are different and seem like an issue with how messages are printed locally. See the `"alwaysCurrent doesn't get rebuilt unless missing"` test.  

I'm going to document that here (when I run just `vizmake('mayfly_nymph')`, I do see `[ BUILD ] data/mayfly_nymph.csv` in the output):
```
suppressWarnings(expect_message(vizmake('mayfly_nymph'), '[ BUILD ] data/mayfly_nymph.csv', fixed=TRUE))
Error: `messages` does not match "[ BUILD ] data/mayfly_nymph.csv".
Actual values:
* [ \033[38;5;226m LOAD\033[39m ] \n
* (       ) vizlab/remake/timestamps/cuyahoga.txt\n
* (       ) vizlab/remake/timestamps/never_current.txt\n
* Starting build at 2018-01-10 08:59:49\n
* [ \033[38;5;226m READ\033[39m ]                                                |  \033[38;5;246m# loading sources\033[39m\n
* < \033[38;5;45m MAKE\033[39m > mayfly_nymph\n
* [ \033[38;5;67mBUILD\033[39m ] arguments_all                                  |  \033[38;5;246marguments_all <- collectItemArgume...\033[39m\n
* [ \033[38;5;226m READ\033[39m ]                                                |  \033[38;5;246m# loading packages\033[39m\n
* [ \033[38;5;67mBUILD\033[39m ] arguments_mayfly_nymph                         |  \033[38;5;246marguments_mayfly_nymph <- getEleme...\033[39m\n
* [ \033[38;5;67mBUILD\033[39m ] vizlab/remake/scripts/mayfly_nymph.R           |  \033[38;5;246mprepSources(outfile = "vizlab/rema...\03
```

I think it's just because extra characters are added locally. I'm :crossed_fingers: that this doesn't happen on Travis.

**Comment by lindsaycarr** [comment]
So a restart didn't work ...

**Comment by aappling-usgs** [comment]
I get the same set of test errors locally regardless of whether i'm running this branch or master. let's merge this PR and lean on a new vizlab issue (#327) to address the warnings and errors.

**Pull request merged**
